from __future__ import annotations

import shutil
from pathlib import Path

from guillotine.ir import ApiSpec


def emit_mcp(spec: ApiSpec, output_dir: Path) -> Path:
    mcp_dir = output_dir / "mcp"
    if mcp_dir.exists():
        shutil.rmtree(mcp_dir)
    mcp_dir.mkdir(parents=True)
    (mcp_dir / "server.py").write_text(_server_source(spec), encoding="utf-8")
    (mcp_dir / "README.md").write_text(_readme(spec), encoding="utf-8")
    return mcp_dir


def _server_source(spec: ApiSpec) -> str:
    env_prefix = spec.package_name.upper()
    return f'''"""Single-tool MCP wrapper for the generated {spec.title} DSL."""

from __future__ import annotations

import os
from pathlib import Path

from guillotine.runtime import execute

try:
    from mcp.server.fastmcp import FastMCP
except ImportError as exc:  # pragma: no cover - optional runtime dependency
    raise SystemExit(
        "This generated MCP wrapper needs the optional mcp package. "
        "Install with: pip install 'guillotine-gen[mcp]'"
    ) from exc


mcp = FastMCP("{spec.package_name}")
GENERATED_ROOT = Path(__file__).resolve().parents[1]
_ENABLED = {{"1", "true", "yes", "on"}}


@mcp.tool()
def exec(code: str, base_url: str | None = None, timeout: float = 30.0) -> dict:
    """Execute Python code against the generated {spec.package_name} DSL.

    SECURITY: the local executor is NOT a sandbox. Code runs with the full
    privileges of this process (filesystem, network, subprocesses). The tool is
    disabled until you opt in by setting GUILLOTINE_ALLOW_EXEC=1, and only in a
    trusted/isolated environment.
    """
    if os.environ.get("GUILLOTINE_ALLOW_EXEC", "").strip().lower() not in _ENABLED:
        return {{
            "returncode": 126,
            "stdout": "",
            "stderr": (
                "Refused: this server runs untrusted Python with no sandbox "
                "(full host access). Set GUILLOTINE_ALLOW_EXEC=1 to enable exec, "
                "and only in a trusted, isolated environment."
            ),
            "result": None,
            "timed_out": False,
        }}
    env = {{}}
    if base_url:
        env["{env_prefix}_BASE_URL"] = base_url
    result = execute(code, extra_paths=[GENERATED_ROOT], env=env, timeout=timeout)
    return result.as_dict()


if __name__ == "__main__":
    mcp.run()
'''


def _readme(spec: ApiSpec) -> str:
    return f"""# {spec.title} MCP Wrapper

This is the code-mode projection generated by Guillotine. It exposes one MCP tool:

- `exec(code, base_url=None, timeout=30.0)`

The tool runs Python with the generated `{spec.package_name}` package on `PYTHONPATH`.
Use generated skills and `{spec.package_name}.cheatsheet()` for progressive disclosure
inside the code.

## Security

The local executor is **not a sandbox**: code runs with the full privileges of the
server process. The `exec` tool is therefore disabled until you opt in:

```bash
export GUILLOTINE_ALLOW_EXEC=1   # only in a trusted, isolated environment
```

The wrapper also deliberately does not accept API tokens as tool arguments. Use it for
public/read-only APIs, or replace the executor with a hardened supervisor before
exposing authenticated secrets.

It needs the package installed: `pip install 'guillotine-gen[mcp]'`.
"""
