from __future__ import annotations

import re
import shutil
from pathlib import Path

from guillotine.ir import ApiSpec, Resource, SafetyTier

AUTO_HEADER = "<!-- Auto-generated by guillotine. Do not edit manually. -->"


def _slug(*parts: str) -> str:
    """Agent Skills names must match ^[a-z0-9]+(-[a-z0-9]+)*$; package_name is a
    Python identifier (underscores), so hyphenate and collapse."""
    joined = "-".join(parts)
    joined = joined.replace("_", "-").lower()
    joined = re.sub(r"-+", "-", joined)
    return joined.strip("-")


def emit_skills(spec: ApiSpec, output_dir: Path) -> Path:
    skills_dir = output_dir / "skills"
    if skills_dir.exists():
        shutil.rmtree(skills_dir)
    skills_dir.mkdir(parents=True)

    (skills_dir / "SKILL.md").write_text(_shared_skill(spec), encoding="utf-8")
    (skills_dir / "index.md").write_text(_index(spec), encoding="utf-8")
    for resource in spec.resources:
        resource_dir = skills_dir / resource.name
        (resource_dir / "references").mkdir(parents=True)
        (resource_dir / "SKILL.md").write_text(
            _resource_skill(spec, resource), encoding="utf-8"
        )
        (resource_dir / "references" / "operations.md").write_text(
            _operations_reference(resource), encoding="utf-8"
        )
    return skills_dir


def _shared_skill(spec: ApiSpec) -> str:
    return f"""---
name: {_slug(spec.package_name, "dsl")}
description: Use when an agent needs to call the generated {spec.title} Python DSL, discover verbs, execute API calls, or inspect generated help.
---
{AUTO_HEADER}

# {spec.title} DSL

Import the generated package and connect once:

```python
import {spec.package_name}
c = {spec.package_name}.connect(base_url="...", token="...")
```

Use `cheatsheet(section=..., grep=...)` before loading a large surface. Use
`help_json("namespace.verb")` when you need exact parameters or enum choices.

Generated verbs return lazy `OperationResult` handles. Call `.head(n)` for one page,
`.all(max_pages=...)` for generated paginated operations, `.one()` for one object,
`.json()` only when you truly need the full payload, and `.run()` for write operations
where the response body is not important.

Every handle exposes `.raw`, the underlying transport. Use it only when a generated
verb is missing a capability.

Destructive generated verbs require `yes=True`; cascade-tier verbs also require
`confirm_name=...`. Treat `SafetyBlocked` as a speed-bump, not authorization.
"""


def _index(spec: ApiSpec) -> str:
    lines = [
        AUTO_HEADER,
        "",
        f"# {spec.title} Skills",
        "",
        "All entries are generated from the same IR as the DSL and MCP wrapper.",
        "",
        "| Skill | Operations | Notes |",
        "|---|---:|---|",
        f"| `{_slug(spec.package_name, 'dsl')}` | all | Shared runtime contract |",
    ]
    for resource in spec.resources:
        destructive = sum(
            1 for op in resource.operations if op.safety_tier >= SafetyTier.DELETE
        )
        note = f"{destructive} destructive" if destructive else "read/write"
        lines.append(
            f"| `{_slug(spec.package_name, resource.name)}` | {len(resource.operations)} | {note} |"
        )
    return "\n".join(lines) + "\n"


def _resource_skill(spec: ApiSpec, resource: Resource) -> str:
    verbs = ", ".join(op.name for op in resource.operations[:12])
    if len(resource.operations) > 12:
        verbs += ", and more"
    return f"""---
name: {_slug(spec.package_name, resource.name)}
description: Use when working with {spec.title} {resource.label} operations through the generated DSL. Verbs include: {verbs}.
---
{AUTO_HEADER}

# {resource.label.title()}

Connect first:

```python
import {spec.package_name}
c = {spec.package_name}.connect(base_url="...", token="...")
```

Discover this namespace without loading the full API:

```python
print({spec.package_name}.cheatsheet(section="{resource.name}"))
print({spec.package_name}.help_json("{resource.name}.{resource.operations[0].name}"))
```

Call verbs on `c.{resource.name}`. Prefer `.head(n)`, `.all(max_pages=...)`, and
`.one()` over `.json()` to keep context small. See `references/operations.md` for the
exact generated operations.
"""


def _operations_reference(resource: Resource) -> str:
    lines = [AUTO_HEADER, "", f"# {resource.label.title()} Operations", ""]
    for op in resource.operations:
        lines.extend(
            [
                f"## `{resource.name}.{op.name}`",
                "",
                f"- HTTP: `{op.method} {op.path}`",
                f"- Operation ID: `{op.operation_id}`",
                f"- Safety tier: `{op.safety_tier.name}`",
            ]
        )
        if op.summary:
            lines.append(f"- Summary: {op.summary}")
        choices = [
            f"`{param.name}` in `{tuple(param.enum)}`"
            for param in op.parameters
            if param.enum
        ]
        if choices:
            lines.append("- Choices: " + ", ".join(choices))
        if op.safety_tier >= SafetyTier.DELETE:
            lines.append(
                "- Destructive: pass `yes=True`; cascade operations also need `confirm_name=`."
            )
        lines.append("")
    return "\n".join(lines)
